NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"
login_check:
    path:     /login_check
    methods:  [POST]
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

good:
    resource: "@AppBundle/Controller/GoodController.php"
    type: rest

order:
    resource: "@AppBundle/Controller/OrderController.php"
    type: rest
